### ISSUE TITLE
Usersnap Feedback - Stuck at "You are logged in!" screen

### ISSUE THREAD

**Issue by DennisBaekgaard** [DennisBaekgaard/IdleGameIssues#26]
**Sender**: benja@bobs.com
**Comment**: http://i.imgur.com/zEHWNbU.png
[Open #18 in Usersnap Dashboard](https://usersnap.com/a/#/company/p/idlegame-4d9242ce/18)

![Usersnap Feedback - Stuck at "You are logged in!" screen](https://usersnappublic.s3.amazonaws.com/2015-10-29/23-56/78ed9ac1-28e8-4968-ba05-75263ba18dbd.png)

**Browser**: Chrome 46 (Windows 10)
**Referer**: [http://hvadsynesdaniel.dk/home](http://hvadsynesdaniel.dk/home)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 391

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by BenjaBobs** [comment]
Found out it happened when visiting http://hvadsynesdaniel.dk/auth/login while already being logged in. Maybe make it re-route to the game page?
