### ISSUE TITLE
Usersnap Feedback - When winning a fight your hp is set to 0

### ISSUE THREAD

**Issue by DennisBaekgaard** [DennisBaekgaard/IdleGameIssues#27]
**Sender**: benja@bobs.com
**Comment**: I don't even
[Open #19 in Usersnap Dashboard](https://usersnap.com/a/#/company/p/idlegame-4d9242ce/19)

![Usersnap Feedback - When winning a fight your hp is set to 0](https://usersnappublic.s3.amazonaws.com/2015-10-30/18-49/946e2953-7758-4ac1-a462-875473b3985c.png)

**Browser**: Chrome 46 (Windows 10)
**Referer**: [http://hvadsynesdaniel.dk/](http://hvadsynesdaniel.dk/)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 955

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by BenjaBobs** [comment]
Console snip: http://i.imgur.com/UODbxfb.png
